# Generated by Django 2.0.5 on 2018-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=200)),
                ('movie_url', models.CharField(max_length=200)),
                ('movie_points', models.IntegerField(max_length=10)),
                ('movie_begin_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('birth', models.DateTimeField(verbose_name='date published')),
                ('create_time', models.DateTimeField(verbose_name='date published')),
                ('dollar', models.IntegerField(max_length=10)),
                ('icon', models.CharField(max_length=200)),
                ('introduce', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=5)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=10)),
                ('type_introduce', models.CharField(max_length=100)),
            ],
        ),
    ]
